"""
OceanEmbed - SIH26066 Backend
==============================
Predicts subsurface ocean temperature & salinity from surface
temperature, surface salinity, depth, latitude, and longitude.

Trained on REAL Argo float data across the Indian Ocean region
(-20 to 30 N, 30 to 100 E, 0-1000m depth). See train_model.py and
argo_data_loader_full_india.py for data provenance.

Run:
    uvicorn main:app --reload --port 8000
"""
import os
from contextlib import asynccontextmanager

import numpy as np
import data_generator
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from model import OceanEmbedPredictor, MODEL_PATH

LAT_MIN, LAT_MAX = -20.0, 30.0
LON_MIN, LON_MAX = 30.0, 100.0
DEPTH_MIN, DEPTH_MAX = 0.0, 1000.0

NOTE = (
    "Model trained on real Argo float observations across the Indian Ocean "
    "region. Predictions are estimates, not guaranteed measurements."
)

FALLBACK_DISCLAIMER = (
    "DEMO/SYNTHETIC DATA: all values are generated by a parametric formula "
    "for prototype/demo purposes only. They are NOT real oceanographic "
    "observations, NOT sourced from satellites or Argo floats, and NOT a "
    "validated forecast."
)

predictor = OceanEmbedPredictor()


def normalize_latlon(lat, lon):
    lat_n = (lat - LAT_MIN) / (LAT_MAX - LAT_MIN)
    lon_n = (lon - LON_MIN) / (LON_MAX - LON_MIN)
    return lat_n, lon_n


def build_feature_vector(surface_temp, surface_sal, depth, lat, lon):
    lat_n, lon_n = normalize_latlon(lat, lon)
    return np.array([surface_temp, surface_sal, depth, lat_n, lon_n], dtype=np.float32)


@asynccontextmanager
async def lifespan(app: FastAPI):
    if not os.path.exists(MODEL_PATH):
        import train_model
        train_model.main()
    predictor.load()
    yield


app = FastAPI(
    title="OceanEmbed SIH26066 API",
    description="Subsurface ocean parameter estimation from real Argo float data. " + NOTE,
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PredictRequest(BaseModel):
    lat: float = Field(..., ge=LAT_MIN, le=LAT_MAX, description="Latitude, deg N")
    lon: float = Field(..., ge=LON_MIN, le=LON_MAX, description="Longitude, deg E")
    depth: float = Field(..., ge=DEPTH_MIN, le=DEPTH_MAX, description="Depth, m")
    # surface fields may be provided by the client; if omitted the server
    # will synthesize them from the demo surface generator.
    surface_temp: float | None = Field(None, description="Sea surface temperature, deg C")
    surface_sal: float | None = Field(None, description="Sea surface salinity, psu")

    class Config:
        json_schema_extra = {
            "example": {"lat": 15.0, "lon": 70.0, "depth": 200.0,
                        "surface_temp": 28.5, "surface_sal": 35.0}
        }


class PredictResponse(BaseModel):
    lat: float
    lon: float
    depth: float
    surface_temp: float
    surface_sal: float
    predicted_temperature_degC: float
    predicted_salinity_psu: float
    # Synthetic reference values and the surface inputs actually used.
    synthetic_reference_temperature_degC: float | None = None
    synthetic_reference_salinity_psu: float | None = None
    surface_inputs_used: dict | None = None
    disclaimer: str | None = None
    note: str = NOTE


@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "OceanEmbed SIH26066 backend",
        "model_loaded": predictor.loaded,
        "note": NOTE,
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.post("/api/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    """Predict subsurface temperature & salinity at a lat/lon/depth point."""
    # If the client did not supply surface fields, synthesize deterministic
    # surface inputs for this lat/lon using the demo generator.
    if req.surface_temp is None or req.surface_sal is None:
        sfields = data_generator.surface_fields(req.lat, req.lon, noise=False)
        surface_temp = float(sfields["sst"].item() if hasattr(sfields["sst"], "item") else sfields["sst"])
        surface_sal = float(sfields["sss"].item() if hasattr(sfields["sss"], "item") else sfields["sss"])
    else:
        surface_temp = float(req.surface_temp)
        surface_sal = float(req.surface_sal)

    fv = build_feature_vector(surface_temp, surface_sal, req.depth, req.lat, req.lon).reshape(1, -1)
    pred = predictor.predict(fv)[0]

    # Compute synthetic reference (parametric demo) for the same inputs so the
    # frontend can compare model output to an interpretable baseline.
    try:
        synth_t, synth_s = data_generator.subsurface_profile(req.lat, req.lon, req.depth, sfields if 'sfields' in locals() else None, noise=False)
        if isinstance(synth_t, np.ndarray):
            synth_t = float(synth_t.item())
            synth_s = float(synth_s.item())
    except Exception:
        synth_t = None
        synth_s = None

    surface_inputs_used = None
    try:
        # If we synthesized surface inputs above, include the full surface
        # fields dictionary so the UI can display all inputs.
        surface_inputs_used = sfields if 'sfields' in locals() else {"sst": surface_temp, "sss": surface_sal}
    except Exception:
        surface_inputs_used = {"sst": surface_temp, "sss": surface_sal}

    return PredictResponse(
        lat=req.lat, lon=req.lon, depth=req.depth,
        surface_temp=surface_temp, surface_sal=surface_sal,
        predicted_temperature_degC=float(pred[0]),
        predicted_salinity_psu=float(pred[1]),
        synthetic_reference_temperature_degC=synth_t,
        synthetic_reference_salinity_psu=synth_s,
        surface_inputs_used=surface_inputs_used,
        disclaimer=FALLBACK_DISCLAIMER,
    )


@app.get("/api/locations")
def get_locations():
    return {
        "locations": data_generator.DEMO_LOCATIONS,
        "domain": {
            "lat_range_degN": [data_generator.LAT_MIN, data_generator.LAT_MAX],
            "lon_range_degE": [data_generator.LON_MIN, data_generator.LON_MAX],
            "depth_range_m": [data_generator.DEPTH_MIN, data_generator.DEPTH_MAX],
        },
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/grid")
def get_grid(resolution: float = 3.0):
    # Build a regular lat/lon grid over the demo domain and return surface
    # fields for every cell so the frontend can render an initial map.
    lat = np.arange(data_generator.LAT_MIN, data_generator.LAT_MAX + 1e-6, resolution)
    lon = np.arange(data_generator.LON_MIN, data_generator.LON_MAX + 1e-6, resolution)
    lat_list = lat.tolist()
    lon_list = lon.tolist()

    s = data_generator.surface_fields(np.repeat(lat[:, None], len(lon), axis=1), np.repeat(lon[None, :], len(lat), axis=0), noise=False)

    # Ensure fields are nested lists [lat_index][lon_index]
    fields = {k: np.array(v).tolist() for k, v in s.items()}

    return {
        "lat": lat_list,
        "lon": lon_list,
        "fields": fields,
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/profile/{location_id}")
def get_profile(location_id: str):
    # Find demo location
    loc = next((l for l in data_generator.DEMO_LOCATIONS if l["location_id"] == location_id), None)
    if loc is None:
        raise HTTPException(404, "Location not found")

    lat = loc["lat"]
    lon = loc["lon"]
    depths = data_generator.DEPTH_LEVELS

    # surface fields (deterministic)
    sfields = data_generator.surface_fields(lat, lon, noise=False)

    # synthetic reference profile
    synth_t, synth_s = data_generator.subsurface_profile(lat, lon, depths, sfields=sfields, noise=False)

    # Build feature vectors for model prediction using the synthetic surface
    # inputs so predicted profile aligns with the surface fields returned.
    fvs = np.column_stack([
        np.repeat(float(sfields["sst"]), len(depths)),
        np.repeat(float(sfields["sss"]), len(depths)),
        np.array(depths, dtype=float),
        np.repeat((lat - LAT_MIN) / (LAT_MAX - LAT_MIN), len(depths)),
        np.repeat((lon - LON_MIN) / (LON_MAX - LON_MIN), len(depths)),
    ])
    preds = predictor.predict(fvs)

    return {
        "location": loc,
        "surface_fields": {k: float(v) for k, v in sfields.items()},
        "depth_m": depths,
        "predicted_temperature_degC": [float(x) for x in preds[:, 0].tolist()],
        "predicted_salinity_psu": [float(x) for x in preds[:, 1].tolist()],
        "synthetic_reference_temperature_degC": [float(x) for x in np.atleast_1d(synth_t).tolist()],
        "synthetic_reference_salinity_psu": [float(x) for x in np.atleast_1d(synth_s).tolist()],
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/validation")
def get_validation():
    """RMSE / correlation / bias computed on a held-out REAL test split."""
    if predictor.metrics is None:
        raise HTTPException(500, "Validation metrics not available. Run train_model.py first.")
    return predictor.metrics