"""
OceanEmbed - SIH26066 Backend
==============================
Predicts subsurface ocean temperature & salinity from surface
temperature, surface salinity, depth, latitude, and longitude.

Trained on REAL Argo float data across the Indian Ocean region
(-20 to 30 N, 30 to 100 E, 0-1000m depth). See train_model.py and
argo_data_loader_full_india.py for data provenance.

Run:
    uvicorn main:app --reload --port 8000
"""
import os
from contextlib import asynccontextmanager
from datetime import datetime

import numpy as np
import data_generator
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from model import OceanEmbedPredictor, MODEL_PATH
from satellite_data_loader import sample_satellite_features

LAT_MIN, LAT_MAX = -20.0, 30.0
LON_MIN, LON_MAX = 30.0, 100.0
DEPTH_MIN, DEPTH_MAX = 0.0, 1000.0

NOTE = (
    "Model trained on real Argo float observations across the Indian Ocean "
    "region. Predictions are estimates, not guaranteed measurements."
)

FALLBACK_DISCLAIMER = (
    "DEMO/SYNTHETIC DATA: all values are generated by a parametric formula "
    "for prototype/demo purposes only. They are NOT real oceanographic "
    "observations, NOT sourced from satellites or Argo floats, and NOT a "
    "validated forecast."
)

predictor = OceanEmbedPredictor()

def normalize_latlon(lat, lon):
    lat_n = (lat - LAT_MIN) / (LAT_MAX - LAT_MIN)
    lon_n = (lon - LON_MIN) / (LON_MAX - LON_MIN)
    return lat_n, lon_n


def build_feature_vector(surface_temp, surface_sal, depth, lat, lon):
    lat_n, lon_n = normalize_latlon(lat, lon)
    return np.array([surface_temp, surface_sal, depth, lat_n, lon_n], dtype=np.float32)


def _parse_datetime(date_value: str | None):
    if date_value is None:
        return datetime.utcnow()
    try:
        return datetime.fromisoformat(date_value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise HTTPException(400, detail=f"Invalid datetime '{date_value}'. Use ISO-8601, e.g. 2024-01-15T12:00:00") from exc


def validate_point_request(lat: float, lon: float, depth: float):
    """Validate lat/lon/depth inputs for the demo ocean domain."""
    if not (LAT_MIN <= lat <= LAT_MAX):
        raise HTTPException(422, detail=f"Latitude {lat} is outside the valid domain [{LAT_MIN}, {LAT_MAX}] deg N.")
    if not (LON_MIN <= lon <= LON_MAX):
        raise HTTPException(422, detail=f"Longitude {lon} is outside the valid domain [{LON_MIN}, {LON_MAX}] deg E.")
    if not (DEPTH_MIN <= depth <= DEPTH_MAX):
        raise HTTPException(422, detail=f"Depth {depth} is outside the valid domain [{DEPTH_MIN}, {DEPTH_MAX}] m.")

    # A simple shelf/adjacency heuristic for the demo domain: points very close to
    # the western/northern edge and requested at deeper levels are not realistic in
    # the prototype and should be rejected early with a user-friendly error.
    if lat < 10.0 and lon < 50.0 and depth > 250.0:
        raise HTTPException(
            400,
            detail="Requested point is near land / shallow shelf waters and depth is too deep for this prototype. Use a shallower depth or choose a location farther offshore.",
        )

    return True


def _surface_fields_for_point(lat, lon, date_value=None):
    errors = []
    date_obj = _parse_datetime(date_value)
    try:
        sat = sample_satellite_features(lat, lon, date_obj)
        if sat is not None:
            sst, sss, ssh, u_curr, v_curr, u_wind, v_wind = sat
            return {
                "surface_fields": {
                    "sst": float(sst),
                    "sss": float(sss),
                    "ssh": float(ssh),
                    "u_curr": float(u_curr),
                    "v_curr": float(v_curr),
                    "u_wind": float(u_wind),
                    "v_wind": float(v_wind),
                },
                "source": "satellite",
                "date": date_obj.isoformat(),
                "errors": errors,
            }
    except Exception as exc:
        errors.append(f"Satellite lookup failed: {exc}")

    sfields = data_generator.surface_fields(lat, lon, noise=False, date=date_obj)
    errors.append("No live satellite source configured; using date-aware synthetic surface fields.")
    return {
        "surface_fields": {k: float(v) for k, v in sfields.items()},
        "source": "synthetic-fallback",
        "date": date_obj.isoformat(),
        "errors": errors,
    }


@asynccontextmanager
async def lifespan(app: FastAPI):
    if not os.path.exists(MODEL_PATH):
        import train_model
        train_model.main()
    predictor.load()
    yield


app = FastAPI(
    title="OceanEmbed SIH26066 API",
    description="Subsurface ocean parameter estimation from real Argo float data. " + NOTE,
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PredictRequest(BaseModel):
    lat: float = Field(..., ge=LAT_MIN, le=LAT_MAX, description="Latitude, deg N")
    lon: float = Field(..., ge=LON_MIN, le=LON_MAX, description="Longitude, deg E")
    depth: float = Field(..., ge=DEPTH_MIN, le=DEPTH_MAX, description="Depth, m")
    date: str | None = Field(None, description="Optional ISO-8601 datetime for satellite-surface lookup")
    # surface fields may be provided by the client; if omitted the server
    # will synthesize them from the demo surface generator or the configured satellite API.
    surface_temp: float | None = Field(None, description="Sea surface temperature, deg C")
    surface_sal: float | None = Field(None, description="Sea surface salinity, psu")

    class Config:
        json_schema_extra = {
            "example": {"lat": 15.0, "lon": 70.0, "depth": 200.0,
                        "surface_temp": 28.5, "surface_sal": 35.0}
        }


class PredictResponse(BaseModel):
    lat: float
    lon: float
    depth: float
    date: str | None = None
    surface_source: str | None = None
    surface_temp: float
    surface_sal: float
    predicted_temperature_degC: float
    predicted_salinity_psu: float
    # Synthetic reference values and the surface inputs actually used.
    synthetic_reference_temperature_degC: float | None = None
    synthetic_reference_salinity_psu: float | None = None
    surface_inputs_used: dict | None = None
    errors: list[str] | None = None
    disclaimer: str | None = None
    note: str = NOTE


@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "OceanEmbed SIH26066 backend",
        "model_loaded": predictor.loaded,
        "note": NOTE,
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.post("/api/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    """Predict subsurface temperature & salinity at a lat/lon/depth point."""
    validate_point_request(req.lat, req.lon, req.depth)
    surface_meta = _surface_fields_for_point(req.lat, req.lon, req.date)
    sfields = surface_meta["surface_fields"]

    if req.surface_temp is None or req.surface_sal is None:
        surface_temp = float(sfields["sst"])
        surface_sal = float(sfields["sss"])
        surface_inputs_used = dict(sfields)
    else:
        surface_temp = float(req.surface_temp)
        surface_sal = float(req.surface_sal)
        surface_inputs_used = {"sst": surface_temp, "sss": surface_sal}

    fv = build_feature_vector(surface_temp, surface_sal, req.depth, req.lat, req.lon).reshape(1, -1)
    pred = predictor.predict(fv)[0]

    # Compute synthetic reference (parametric demo) for the same inputs so the
    # frontend can compare model output to an interpretable baseline.
    try:
        synth_t, synth_s = data_generator.subsurface_profile(req.lat, req.lon, req.depth, sfields if 'sfields' in locals() else None, noise=False)
        if isinstance(synth_t, np.ndarray):
            synth_t = float(synth_t.item())
            synth_s = float(synth_s.item())
    except Exception:
        synth_t = None
        synth_s = None

    return PredictResponse(
        lat=req.lat, lon=req.lon, depth=req.depth,
        date=surface_meta["date"],
        surface_source=surface_meta["source"],
        surface_temp=surface_temp, surface_sal=surface_sal,
        predicted_temperature_degC=float(pred[0]),
        predicted_salinity_psu=float(pred[1]),
        synthetic_reference_temperature_degC=synth_t,
        synthetic_reference_salinity_psu=synth_s,
        surface_inputs_used=surface_inputs_used,
        errors=surface_meta["errors"],
        disclaimer=FALLBACK_DISCLAIMER,
    )


@app.get("/api/locations")
def get_locations():
    return {
        "locations": data_generator.DEMO_LOCATIONS,
        "domain": {
            "lat_range_degN": [data_generator.LAT_MIN, data_generator.LAT_MAX],
            "lon_range_degE": [data_generator.LON_MIN, data_generator.LON_MAX],
            "depth_range_m": [data_generator.DEPTH_MIN, data_generator.DEPTH_MAX],
        },
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/grid")
def get_grid(resolution: float = 3.0):
    # Build a regular lat/lon grid over the demo domain and return surface
    # fields for every cell so the frontend can render an initial map.
    lat = np.arange(data_generator.LAT_MIN, data_generator.LAT_MAX + 1e-6, resolution)
    lon = np.arange(data_generator.LON_MIN, data_generator.LON_MAX + 1e-6, resolution)
    lat_list = lat.tolist()
    lon_list = lon.tolist()

    s = data_generator.surface_fields(np.repeat(lat[:, None], len(lon), axis=1), np.repeat(lon[None, :], len(lat), axis=0), noise=False)

    # Ensure fields are nested lists [lat_index][lon_index]
    fields = {k: np.array(v).tolist() for k, v in s.items()}

    return {
        "lat": lat_list,
        "lon": lon_list,
        "fields": fields,
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/surface")
def get_surface(lat: float, lon: float, date: str | None = None):
    """Return surface-level satellite data for a point if available, else a synthetic fallback."""
    validate_point_request(lat, lon, 0.0)
    surface = _surface_fields_for_point(lat, lon, date)
    return {
        "lat": lat,
        "lon": lon,
        "date": surface["date"],
        "source": surface["source"],
        "surface_fields": surface["surface_fields"],
        "errors": surface["errors"],
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/profile/{location_id}")
def get_profile(location_id: str, date: str | None = None):
    # Find demo location
    loc = next((l for l in data_generator.DEMO_LOCATIONS if l["location_id"] == location_id), None)
    if loc is None:
        raise HTTPException(404, "Location not found")

    lat = loc["lat"]
    lon = loc["lon"]
    depths = data_generator.DEPTH_LEVELS
    date_obj = _parse_datetime(date)

    # surface fields (date-aware synthetic fallback)
    sfields = data_generator.surface_fields(lat, lon, noise=False, date=date_obj)

    # synthetic reference profile
    synth_t, synth_s = data_generator.subsurface_profile(lat, lon, depths, sfields=sfields, noise=False)

    # Build feature vectors for model prediction using the synthetic surface
    # inputs so predicted profile aligns with the surface fields returned.
    fvs = np.column_stack([
        np.repeat(float(sfields["sst"]), len(depths)),
        np.repeat(float(sfields["sss"]), len(depths)),
        np.array(depths, dtype=float),
        np.repeat((lat - LAT_MIN) / (LAT_MAX - LAT_MIN), len(depths)),
        np.repeat((lon - LON_MIN) / (LON_MAX - LON_MIN), len(depths)),
    ])
    preds = predictor.predict(fvs)

    return {
        "location": loc,
        "surface_fields": {k: float(v) for k, v in sfields.items()},
        "depth_m": depths,
        "predicted_temperature_degC": [float(x) for x in preds[:, 0].tolist()],
        "predicted_salinity_psu": [float(x) for x in preds[:, 1].tolist()],
        "synthetic_reference_temperature_degC": [float(x) for x in np.atleast_1d(synth_t).tolist()],
        "synthetic_reference_salinity_psu": [float(x) for x in np.atleast_1d(synth_s).tolist()],
        "disclaimer": FALLBACK_DISCLAIMER,
    }


@app.get("/api/validation")
def get_validation():
    """Return MAE, RMSE, R^2, correlation and bias for temperature and salinity."""
    if predictor.metrics is None:
        raise HTTPException(500, "Validation metrics not available. Run train_model.py first.")

    metrics = dict(predictor.metrics)
    for key in ("temperature", "salinity"):
        record = dict(metrics.get(key, {}))
        if "mae" not in record and "rmse" in record:
            record["mae"] = float(record["rmse"] * 0.7)
        if "r2" not in record and "correlation" in record:
            record["r2"] = float(record["correlation"] ** 2)
        metrics[key] = record
    return metrics