// OceanEmbed API client
// Talks to the FastAPI backend in oceanembed_backend/main.py.
// Every value shown in the UI is either a direct API response field or is
// assembled purely from repeated real calls to /api/predict — nothing here
// fabricates ocean data client-side.

export const API_BASE = (
  import.meta.env.VITE_API_BASE_URL || "http://localhost:8000"
).replace(/\/+$/, "");

// Fallback domain / depth levels, used only until /api/locations responds.
// These mirror data_generator.py exactly so the map renders instantly.
export const DEFAULT_DOMAIN = {
  lat_range_degN: [5.0, 30.0],
  lon_range_degE: [45.0, 105.0],
  depth_range_m: [0.0, 1000.0],
};

export const DEPTH_LEVELS = [
  0, 10, 20, 30, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500, 600, 700,
  800, 900, 1000,
];

export const FALLBACK_DISCLAIMER =
  "DEMO/SYNTHETIC DATA: all values are generated by a parametric formula for " +
  "prototype/demo purposes only. They are NOT real oceanographic observations, " +
  "NOT sourced from satellites or Argo floats, and NOT a validated forecast.";

class ApiError extends Error {}

async function request(path, { method = "GET", body, timeoutMs = 15000 } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`${API_BASE}${path}`, {
      method,
      headers: body ? { "Content-Type": "application/json" } : undefined,
      body: body ? JSON.stringify(body) : undefined,
      signal: controller.signal,
    });
    if (!res.ok) {
      let detail = res.statusText;
      try {
        const j = await res.json();
        detail = j.detail ? JSON.stringify(j.detail) : detail;
      } catch {
        /* ignore non-JSON error bodies */
      }
      throw new ApiError(`${method} ${path} failed (${res.status}): ${detail}`);
    }
    return await res.json();
  } catch (err) {
    if (err.name === "AbortError") {
      throw new ApiError(`${method} ${path} timed out after ${timeoutMs}ms`);
    }
    if (err instanceof ApiError) throw err;
    throw new ApiError(
      `Could not reach OceanEmbed backend at ${API_BASE}${path}. Is uvicorn running? (${err.message})`
    );
  } finally {
    clearTimeout(timer);
  }
}

export const getHealth = () => request("/health");

export const getLocations = () => request("/api/locations");

export const getGrid = (resolution = 3.0) =>
  request(`/api/grid?resolution=${resolution}`);

export const getProfile = (locationId, date = null) => {
  const qs = date ? `?date=${encodeURIComponent(date)}` : "";
  return request(`/api/profile/${encodeURIComponent(locationId)}${qs}`);
};

export const predictPoint = (payload) =>
  request("/api/predict", { method: "POST", body: payload });

export const getValidation = () => request("/api/validation", { timeoutMs: 60000 });

/**
 * Run many /api/predict calls with a bounded number in flight at once.
 * Returns results in the same order as `points`; a point that fails is
 * returned as null rather than aborting the whole batch, so one bad cell
 * doesn't blank the whole grid/profile.
 */
export async function predictBatch(points, { concurrency = 12 } = {}) {
  const results = new Array(points.length).fill(null);
  let cursor = 0;

  async function worker() {
    while (true) {
      const i = cursor++;
      if (i >= points.length) return;
      try {
        results[i] = await predictPoint(points[i]);
      } catch {
        results[i] = null;
      }
    }
  }

  const workerCount = Math.max(1, Math.min(concurrency, points.length));
  await Promise.all(Array.from({ length: workerCount }, worker));
  return results;
}

/**
 * Build a full 0-1000m profile for an arbitrary map-click location by
 * calling /api/predict once per standard depth level. Mirrors the shape of
 * GET /api/profile/{location_id}, but works for any lat/lon in the domain
 * (the profile endpoint only knows the fixed demo location IDs).
 */
export async function buildCustomProfile(lat, lon, { concurrency = 8, date = null } = {}) {
  const points = DEPTH_LEVELS.map((depth) => ({ lat, lon, depth, ...(date ? { date } : {}) }));
  const results = await predictBatch(points, { concurrency });

  const depth_m = [];
  const predicted_temperature_degC = [];
  const predicted_salinity_psu = [];
  const synthetic_reference_temperature_degC = [];
  const synthetic_reference_salinity_psu = [];
  let surface_fields = null;
  let failures = 0;

  results.forEach((r, i) => {
    if (!r) {
      failures += 1;
      return;
    }
    depth_m.push(DEPTH_LEVELS[i]);
    predicted_temperature_degC.push(r.predicted_temperature_degC);
    predicted_salinity_psu.push(r.predicted_salinity_psu);
    synthetic_reference_temperature_degC.push(r.synthetic_reference_temperature_degC);
    synthetic_reference_salinity_psu.push(r.synthetic_reference_salinity_psu);
    if (!surface_fields) surface_fields = r.surface_inputs_used;
  });

  if (depth_m.length === 0) {
    throw new ApiError("Could not build a profile for this point — every /api/predict call failed.");
  }

  return {
    location: { location_id: null, name: "Custom Point", lat, lon },
    surface_fields,
    depth_m,
    predicted_temperature_degC,
    predicted_salinity_psu,
    synthetic_reference_temperature_degC,
    synthetic_reference_salinity_psu,
    disclaimer: FALLBACK_DISCLAIMER,
    partial: failures > 0,
  };
}

/**
 * Recompute the map temperature layer at a given depth.
 * At depth 0 this just reuses the SST field already returned by /api/grid.
 * For any other depth it calls /api/predict once per grid cell, passing the
 * exact surface fields from /api/grid as overrides so the result is
 * consistent with what /api/profile or /api/predict would say for that cell.
 */
export async function computeHeatmapAtDepth(gridSurface, depth, { concurrency = 16, date = null } = {}) {
  const { lat, lon, fields } = gridSurface;

  if (Number(depth) === 0) {
    return fields.sst.map((row) => row.slice());
  }

  const points = [];
  for (let i = 0; i < lat.length; i++) {
    for (let j = 0; j < lon.length; j++) {
      points.push({
        lat: lat[i],
        lon: lon[j],
        depth,
        ...(date ? { date } : {}),
        sst: fields.sst[i][j],
        sss: fields.sss[i][j],
        ssh: fields.ssh[i][j],
        u_curr: fields.u_curr[i][j],
        v_curr: fields.v_curr[i][j],
        u_wind: fields.u_wind[i][j],
        v_wind: fields.v_wind[i][j],
      });
    }
  }

  const results = await predictBatch(points, { concurrency });

  const grid = [];
  let k = 0;
  for (let i = 0; i < lat.length; i++) {
    const row = [];
    for (let j = 0; j < lon.length; j++) {
      const r = results[k++];
      row.push(r ? r.predicted_temperature_degC : null);
    }
    grid.push(row);
  }
  return grid;
}
